# Array Operations


In [5]:
import numpy as np

## Array Reshaping

$$
\begin{array}{c}
\begin{bmatrix}
1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9 & 10 & 11 & 12
\end{bmatrix} \\
(1, 12) \\[1em]
\text{Original}
\end{array}
\quad
\xrightarrow{\text{reshape} \\[1ex]}
\quad
\begin{array}{c}
\begin{bmatrix}
1 & 2 & 3 & 4 \\
5 & 6 & 7 & 8 \\
9 & 10 & 11 & 12
\end{bmatrix} \\
(3, 4) \\[1em]
\text{Reshaped Array}
\end{array}
$$


### Flatten

$$
\begin{array}{c}
\begin{bmatrix}
1 & 2 & 3 & 4 \\
5 & 6 & 7 & 8 \\
9 & 10 & 11 & 12
\end{bmatrix} \\
(3, 4) \\[1em]
\text{Reshaped Array}
\end{array}
\quad
\xrightarrow{\text{flatten}}
\quad
\begin{array}{c}
\begin{bmatrix}
1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9 & 10 & 11 & 12
\end{bmatrix} \\
(1, 12) \\[1em]
\text{Flattened Array}
\end{array}
$$


In [6]:
array = np.arange(1, 13)
print("Original Array:\n", array)

reshaped = array.reshape((3, 4))
print("\nReshaped Array:\n", reshaped)

flattened = reshaped.flatten()
print("\nFlattened Array:\n", flattened)

Original Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Flattened Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


### Reshaped Array and Ravelled View modifications:

$$
\begin{array}{c}
\begin{bmatrix}
\color{yellow}{100} & 2 & 3 & 4 \\
5 & 6 & 7 & 8 \\
9 & 10 & 11 & 12
\end{bmatrix} \\
(3, 4) \\[1em]
\text{Reshaped Array}
\end{array}
\quad
\xleftrightarrow{\text{reflects}}
\quad
\begin{array}{c}
\begin{bmatrix}
\color{yellow}{100} & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9 & 10 & 11 & 12
\end{bmatrix} \\
(1,12) \\[1em]
\text{Ravelled View}
\end{array}
$$


In [7]:
ravelled = reshaped.ravel()
print("Revelled View:\n", ravelled)

ravelled[0] = 100
print("\nModified Revelled:\n", ravelled)
print("Updated Reshaped:\n", reshaped)

reshaped[0, 0] = 1000
print("\nModified Reshaped:\n", reshaped)
print("Updated Ravelled:\n", ravelled)

Revelled View:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

Modified Revelled:
 [100   2   3   4   5   6   7   8   9  10  11  12]
Updated Reshaped:
 [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]

Modified Reshaped:
 [[1000    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]
Updated Ravelled:
 [1000    2    3    4    5    6    7    8    9   10   11   12]


## Transpose

$$
\text{A} =
\begin{array}{c}
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix} \\[1.5em]
\text{Original}
\end{array}
\quad
\text{A}^T =
\begin{array}{c}
\begin{bmatrix}
1 & 4 & 7 \\
2 & 5 & 8 \\
3 & 6 & 9
\end{bmatrix} \\[1.5em]
\text{Transposed}
\end{array}
$$


In [8]:
matrix = np.arange(1, 10).reshape((3, 3))
transposed = matrix.T  # Alternative: np.transpose(array)
print("Original:\n", matrix)
print("Transposed:\n", transposed)

Original:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transposed:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


## Flip


In [13]:
array = np.random.randint(10, 99, 6).reshape(3, 2)

fully_flipped_array = np.flip(array)
row_flipped_array = np.flip(array, axis=0)
column_flipped_array = np.flip(array, axis=1)

print("Original Array:\n", array)
print("\nFully Flipped Array (all elements reversed):\n", fully_flipped_array)
print("\nRow-wise Flipped Array (rows reversed):\n", row_flipped_array)
print("\nColumn-wise Flipped Array (columns reversed):\n", column_flipped_array)

Original Array:
 [[30 82]
 [26 17]
 [58 35]]

Fully Flipped Array (all elements reversed):
 [[35 58]
 [17 26]
 [82 30]]

Row-wise Flipped Array (rows reversed):
 [[58 35]
 [26 17]
 [30 82]]

Column-wise Flipped Array (columns reversed):
 [[82 30]
 [17 26]
 [35 58]]
