## Broadcasting:


In [1]:
import numpy as np

<div align=center>

![image](https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png)

</div>


#### Operation of different size arrays:


In [2]:
array1 = np.arange(6).reshape(2, 3)
array2 = np.arange(1, 4)

print("Array 1:\n", array1)
print("Array 2:\n", array2)

print("Array 1 + Array 2:\n", array1 + array2)

Array 1:
 [[0 1 2]
 [3 4 5]]
Array 2:
 [1 2 3]
Array 1 + Array 2:
 [[1 3 5]
 [4 6 8]]


In [3]:
array1 = np.arange(3).reshape(3, 1)
array2 = np.arange(1, 4)

print("Array 1:\n", array1)
print("Array 2:\n", array2)

print("Array 1 + Array 2:\n", array1 + array2)

Array 1:
 [[0]
 [1]
 [2]]
Array 2:
 [1 2 3]
Array 1 + Array 2:
 [[1 2 3]
 [2 3 4]
 [3 4 5]]


In [4]:
array1 = np.arange(3)
array2 = np.arange(4).reshape(4, 1)

print("Array 1:\n", array1)
print("Array 2:\n", array2)

print("Array 1 + Array 2:\n", array1 + array2)

Array 1:
 [0 1 2]
Array 2:
 [[0]
 [1]
 [2]
 [3]]
Array 1 + Array 2:
 [[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [5]:
# Cannot be Broadcasted
array1 = np.arange(12).reshape(3, 4)
array2 = np.arange(4).reshape(4, 1)

print("Array 1:\n", array1)
print("Array 2:\n", array2)

print("Array 1 + Array 2:\n", array1 + array2)

Array 1:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Array 2:
 [[0]
 [1]
 [2]
 [3]]


ValueError: operands could not be broadcast together with shapes (3,4) (4,1) 