# Modifying Elements


In [1]:
import numpy as np

## Indexing and Slicing


In [2]:
array = np.arange(1, 11)
print("Array:", array)
print("Particular Element:", array[5])
print("Range of Elements:", array[2:9])
print("Range of Elements with step:", array[2:9:2])

Array: [ 1  2  3  4  5  6  7  8  9 10]
Particular Element: 6
Range of Elements: [3 4 5 6 7 8 9]
Range of Elements with step: [3 5 7 9]


In [3]:
# fmt:off
array2D = np.array(
  [
    [1,2,3],
    [4,5,6],
    [7,8,9]
  ]
)
print("Particular Element:",array2D[0,1])
print("Entire Row:",array2D[1])
print("Entire Column:",array2D[:,1])

Particular Element: 2
Entire Row: [4 5 6]
Entire Column: [2 5 8]


In [4]:
array3D = np.arange(1, 28).reshape((3, 3, 3))
print("3D Array:\n", array3D)
print("\nSecond 2D array:\n", array3D[1])
print("\nFirst 2D array (3rd Row):\n", array3D[0, 2])
print("\nThird 2D array (1st Column):\n", array3D[2, :, 0])
print("\n3D Array (3rd Row):\n", array3D[:, 2])
print(
    "\nFirst and Third 2D array (1st Row - 1st and 3rd Column):\n", array3D[::2, 0, ::2]
)
# ... is used as shorthand for multiple colons and commas - array3D[:,:,-1]
print("\nLast Column:\n", array3D[..., -1])

3D Array:
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

Second 2D array:
 [[10 11 12]
 [13 14 15]
 [16 17 18]]

First 2D array (3rd Row):
 [7 8 9]

Third 2D array (1st Column):
 [19 22 25]

3D Array (3rd Row):
 [[ 7  8  9]
 [16 17 18]
 [25 26 27]]

First and Third 2D array (1st Row - 1st and 3rd Column):
 [[ 1  3]
 [19 21]]

Last Column:
 [[ 3  6  9]
 [12 15 18]
 [21 24 27]]


### Fancy Indexing


In [5]:
matrix = np.arange(1, 25).reshape((6, 4))
print("Matrix:\n", matrix)
print("Fancy Indexing:\n", matrix[[1, 0, 3, 4]])

Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
Fancy Indexing:
 [[ 5  6  7  8]
 [ 1  2  3  4]
 [13 14 15 16]
 [17 18 19 20]]


### Boolean Indexing


In [6]:
randint_array = np.random.randint(1, 100, (3, 3))
print("Array:\n", randint_array)
mask = randint_array > 45
print("\nArray > 45 (Mask):\n", mask)
print(
    "\nArray with elements > 5:\n", randint_array[mask]
)  # Alternative: randint_array[randint_array > 45]

Array:
 [[86 59 97]
 [39 84 70]
 [83 88 75]]

Array > 45 (Mask):
 [[ True  True  True]
 [False  True  True]
 [ True  True  True]]

Array with elements > 5:
 [86 59 97 84 70 83 88 75]


In [7]:
# Array with numbers > 25 and even
array = np.random.randint(10, 100, 10)
print("Array:", array)

condition_array = array[(array > 25) & (array % 2 == 0)]
print("Array with numbers > 25 and Even:", condition_array)

Array: [27 47 53 33 92 53 73 64 95 90]
Array with numbers > 25 and Even: [92 64 90]


## Adding Elements


### Appending

- Returns new array with appended elements
- New array shape changes to 1D if no axis is given


In [8]:
# 1D array append
array = np.arange(5)
print("Before Array:", array)
print("Array with appending 5:", np.append(array, 5))
print("After Array:", array)

Before Array: [0 1 2 3 4]
Array with appending 5: [0 1 2 3 4 5]
After Array: [0 1 2 3 4]


In [9]:
# 2D array append
a = np.arange(6).reshape(2, 3)
b = np.arange(6, 12).reshape(2, 3)

print("Array 1:\n", a)
print("Array 2:\n", b)

# Append scalar
print("\nAppending scalar 5 to Array 1 (flattened):\n", np.append(a, 5))

# Append Array 2 to Array 1 (flattened)
print("\nAppending Array 2 to Array 1 (flattened):\n", np.append(a, b))

# Append along rows (axis=0)
print("\nAppending Array 2 to Array 1 along rows (axis=0):\n", np.append(a, b, axis=0))

# Append along columns (axis=1)
print(
    "\nAppending Array 2 to Array 1 along columns (axis=1):\n", np.append(a, b, axis=1)
)

Array 1:
 [[0 1 2]
 [3 4 5]]
Array 2:
 [[ 6  7  8]
 [ 9 10 11]]

Appending scalar 5 to Array 1 (flattened):
 [0 1 2 3 4 5 5]

Appending Array 2 to Array 1 (flattened):
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Appending Array 2 to Array 1 along rows (axis=0):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Appending Array 2 to Array 1 along columns (axis=1):
 [[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


### Concatenation

- Returns new array with Concatenated elements
- Requires arrays to be in same size


In [10]:
array1 = np.arange(0, 6)
array2 = np.arange(6, 11)

combined = np.concatenate((array1, array2))

print("Array 1:", array1)
print("Array 2:", array2)
print("Combined Array:", combined)

Array 1: [0 1 2 3 4 5]
Array 2: [ 6  7  8  9 10]
Combined Array: [ 0  1  2  3  4  5  6  7  8  9 10]


In [11]:
a = np.arange(4).reshape(2, 2)
b = np.arange(4, 8).reshape(2, 2)

print("Array 1:\n", a)
print("Array 2:\n", b)
print("\nConcatenated along Row:\n", np.concatenate((a, b), axis=0))
print("\nConcatenated along Column:\n", np.concatenate((a, b), axis=1))

Array 1:
 [[0 1]
 [2 3]]
Array 2:
 [[4 5]
 [6 7]]

Concatenated along Row:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]

Concatenated along Column:
 [[0 1 4 5]
 [2 3 6 7]]


## Replacing Elements

- Affects original array
- Does not return array


In [12]:
array = np.array([10, 20, 30, 40, 50])
print("Before:", array)

np.put(array, [1, 3], [25, 55])
print("After:", array)

Before: [10 20 30 40 50]
After: [10 25 30 55 50]


## Deleting Elements

- Does not delete elements from original array
- Returns new array after deleting elements


In [13]:
array = np.arange(6)
delete_single = np.delete(array, 3)
delete_multiple = np.delete(array, (1, 3, 4))
print("Before Deleting:", array)
print("Deleting single element:", delete_single)
print("Deleting multiple elements:", delete_multiple)
print("After Deleting:", array)

Before Deleting: [0 1 2 3 4 5]
Deleting single element: [0 1 2 4 5]
Deleting multiple elements: [0 2 5]
After Deleting: [0 1 2 3 4 5]


## Stacking

$$
\begin{array}{ccc}
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
&
+
&
\begin{bmatrix}
\textcolor{yellow}{5} & \textcolor{yellow}{6}
\end{bmatrix}
\\[1em]
\text{Original} & & \text{New Row}
\end{array}
\quad
\xrightarrow{\text{Vertical Stack}}
\quad
\begin{array}{c}
\begin{bmatrix}
1 & 2 \\
3 & 4 \\
\textcolor{yellow}{5} & \textcolor{yellow}{6}
\end{bmatrix} \\[1.5em]
\text{New Matrix}
\end{array}

\\[3em]

\begin{array}{ccc}
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
&
+
&
\begin{bmatrix}
\textcolor{cyan}{7} \\
\textcolor{cyan}{8}
\end{bmatrix}
\\[1em]
\text{Original} & & \text{New Column}
\end{array}
\quad
\xrightarrow{\text{Horizontal Stack}}
\quad
\begin{array}{c}
\begin{bmatrix}
1 & 2 & \textcolor{cyan}{7} \\
3 & 4 & \textcolor{cyan}{8}
\end{bmatrix} \\[1.5em]
\text{New Matrix}
\end{array}
$$


In [14]:
# fmt:off
original = np.array(
  [
    [1,2],
    [3,4]
  ]
)

new_row = np.array(
  [
    [5,6]
  ]
)

new_column = np.array(
  [
    [7],
    [8]
  ]
)

new_row_matrix = np.vstack((original, new_row))
new_column_matrix = np.hstack((original, new_column))

print("Original:\n", original)

print("\nNew Row:\n", new_row)
print("Matrix with new Row:\n", new_row_matrix)

print("\nNew Column:\n", new_column)
print("\nMatrix with new Column:\n", new_column_matrix)

Original:
 [[1 2]
 [3 4]]

New Row:
 [[5 6]]
Matrix with new Row:
 [[1 2]
 [3 4]
 [5 6]]

New Column:
 [[7]
 [8]]

Matrix with new Column:
 [[1 2 7]
 [3 4 8]]


## Splitting

$$
\quad
\begin{bmatrix}
\textcolor{orange}{1} & \textcolor{orange}{2} & \textcolor{lime}{3} & \textcolor{lime}{4} \\
\textcolor{orange}{5} & \textcolor{orange}{6} & \textcolor{lime}{7} & \textcolor{lime}{8} \\
\textcolor{orange}{9} & \textcolor{orange}{10} & \textcolor{lime}{11} & \textcolor{lime}{12} \\
\textcolor{orange}{13} & \textcolor{orange}{14} & \textcolor{lime}{15} & \textcolor{lime}{16}
\end{bmatrix}
\quad \xrightarrow{\text{Vertically Split into 2}} \quad
\begin{bmatrix}
\textcolor{orange}{1} & \textcolor{orange}{2} \\
\textcolor{orange}{5} & \textcolor{orange}{6} \\
\textcolor{orange}{9} & \textcolor{orange}{10} \\
\textcolor{orange}{13} & \textcolor{orange}{14}
\end{bmatrix},
\quad
\begin{bmatrix}
\textcolor{lime}{3} & \textcolor{lime}{4} \\
\textcolor{lime}{7} & \textcolor{lime}{8} \\
\textcolor{lime}{11} & \textcolor{lime}{12} \\
\textcolor{lime}{15} & \textcolor{lime}{16}
\end{bmatrix}

\\[2ex]

\begin{bmatrix}
\textcolor{violet}{1} & \textcolor{violet}{2} & \textcolor{violet}{3} & \textcolor{violet}{4} \\
\textcolor{violet}{5} & \textcolor{violet}{6} & \textcolor{violet}{7} & \textcolor{violet}{8} \\
\textcolor{cyan}{9} & \textcolor{cyan}{10} & \textcolor{cyan}{11} & \textcolor{cyan}{12} \\
\textcolor{cyan}{13} & \textcolor{cyan}{14} & \textcolor{cyan}{15} & \textcolor{cyan}{16}
\end{bmatrix}
\quad \xrightarrow{\text{Horizontally Split into 2}} \quad
\begin{bmatrix}
\textcolor{violet}{1} & \textcolor{violet}{2} & \textcolor{violet}{3} & \textcolor{violet}{4} \\
\textcolor{violet}{5} & \textcolor{violet}{6} & \textcolor{violet}{7} & \textcolor{violet}{8}
\end{bmatrix},
\quad
\begin{bmatrix}
\textcolor{cyan}{9} & \textcolor{cyan}{10} & \textcolor{cyan}{11} & \textcolor{cyan}{12} \\
\textcolor{cyan}{13} & \textcolor{cyan}{14} & \textcolor{cyan}{15} & \textcolor{cyan}{16}
\end{bmatrix}
$$


### Vertically and Horizontally splitting


In [15]:
# fmt:off
original = np.arange(1, 17).reshape((4, 4))

# Vertically split - np.hsplit() (column-wise blocks)
columns = np.hsplit(original, 2)
for index, column in enumerate(columns):
    print(f"Vertical Split {index}:\n{column}\n")

# Horizontally split - np.vsplit()  (row-wise blocks)
rows = np.vsplit(original, 2)
for index, row in enumerate(rows):
    print(f"Horizontal Split {index}:\n{row}\n")

Vertical Split 0:
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]

Vertical Split 1:
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]

Horizontal Split 0:
[[1 2 3 4]
 [5 6 7 8]]

Horizontal Split 1:
[[ 9 10 11 12]
 [13 14 15 16]]



### 1D Array splitting


In [16]:
array = np.arange(9)

# Split array evenly into 3 equal parts (must divide exactly)
splitted = np.split(array, 3)
print("Array:", array)
print("Evenly Splitted Array into 3:")
for i in splitted:
    print(i)

# Split array at index 2
splitted2 = np.split(array, [2])
print("\nSplitted Array at 2:")
for i in splitted2:
    print(i)

# Split array at multiple indices: 1, 3, and 7
splitted3 = np.split(array, [1, 3, 7])
print("\nSplitted Array at 1, 3 and 7:")
for i in splitted3:
    print(i)

Array: [0 1 2 3 4 5 6 7 8]
Evenly Splitted Array into 3:
[0 1 2]
[3 4 5]
[6 7 8]

Splitted Array at 2:
[0 1]
[2 3 4 5 6 7 8]

Splitted Array at 1, 3 and 7:
[0]
[1 2]
[3 4 5 6]
[7 8]


In [17]:
# Split the array into 3 parts (can be uneven)
# np.array_split allows unequal splits if the array size is not divisible
splitted = np.array_split(array, 3)

print("Array:", array)
print("\nSplit into 3 (possibly uneven) parts:")
for i, part in enumerate(splitted, 1):
    print(f"Part {i}:", part)

Array: [0 1 2 3 4 5 6 7 8]

Split into 3 (possibly uneven) parts:
Part 1: [0 1 2]
Part 2: [3 4 5]
Part 3: [6 7 8]


## Sorting


In [18]:
unsorted = np.random.randint(1, 100, 10)
print("Unsorted Array:", unsorted)
print("Sorted Array:", np.sort(unsorted))
print("Reverse Sorted Array:", np.sort(unsorted)[::-1])

Unsorted Array: [99 39 54 15 18 16 63 42 23 40]
Sorted Array: [15 16 18 23 39 40 42 54 63 99]
Reverse Sorted Array: [99 63 54 42 40 39 23 18 16 15]


In [19]:
# fmt:off
unsorted2D = np.random.randint(1,10,6).reshape(3,2)
print("Unsorted Matrix:\n", unsorted2D)
print("Sort Matrix by Column:\n", np.sort(unsorted2D, axis=0))
print("Sort Matrix by Row:\n", np.sort(unsorted2D, axis=1))

Unsorted Matrix:
 [[1 9]
 [9 5]
 [6 1]]
Sort Matrix by Column:
 [[1 1]
 [6 5]
 [9 9]]
Sort Matrix by Row:
 [[1 9]
 [5 9]
 [1 6]]


## Filtering


In [20]:
numbers = np.arange(1, 11)
even_numbers = numbers[numbers % 2 == 0]
print("Even Numbers:", even_numbers)

Even Numbers: [ 2  4  6  8 10]


### Where - returns indices of array which satisfy condition:


In [21]:
numbers = np.arange(10)
print("Numbers:", numbers)

where_result = np.where(numbers > 5)  # <condition>
print("Where result (numbers > 5):", where_result)
print("Greater than 5:", numbers[where_result])

condition_array = np.where(
    numbers > 5, numbers * 10, numbers * 2
)  # <condition, True operation, False operation>

print("Condition Array:", condition_array)

# np.where() is similar to
# for index, value in enumerate(numbers):
#     if value > 5: (condition)
#         numbers[index] = value*10 (True operation)
#     else:
#         numbers[index] = value*2 (False operation)

Numbers: [0 1 2 3 4 5 6 7 8 9]
Where result (numbers > 5): (array([6, 7, 8, 9]),)
Greater than 5: [6 7 8 9]
Condition Array: [ 0  2  4  6  8 10 60 70 80 90]


## Missing values


In [22]:
a = np.array([1, 2, 3, np.nan, 5, 6, 7, np.nan, 9, 10])
print("Array with missing values:", a)
print("Missing Values:", np.isnan(a))
print("Array without missing values:", a[~np.isnan(a)])  # ~ is for inverting (negation)

Array with missing values: [ 1.  2.  3. nan  5.  6.  7. nan  9. 10.]
Missing Values: [False False False  True False False False  True False False]
Array without missing values: [ 1.  2.  3.  5.  6.  7.  9. 10.]


## Iterating


In [23]:
# 1D Array - iterates each element
for item in array:
    print(item)

0
1
2
3
4
5
6
7
8


In [24]:
# 2D Array - iterates each row
for row in array2D:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [25]:
# 3D Array - iterates each matrix (2D array)
for matrix in array3D:
    print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[19 20 21]
 [22 23 24]
 [25 26 27]]


In [26]:
# Iterating each element in n-dimensional array
tensor = np.arange(1, 17).reshape((2, 2, 2, 2))
for i in np.nditer(tensor):
    print(i, end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 