# Utility Functions


In [1]:
import numpy as np

### Diagonal Matrix of 1


In [2]:
diagonal = np.eye(4, 3)
print("Diagonal Matrix:\n", diagonal)

Diagonal Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


### Diagonal Matrix of custom values

- Returns matrix of custom values along diagonals
- If diagonal matrix is passed, it returns values at diagonals


In [3]:
diagonal = np.diag([10, 20, 30])
values = np.diag(diagonal)
print("Custom Diagonal Matrix:\n", diagonal)
print("Diagonal Values:\n", values)

Custom Diagonal Matrix:
 [[10  0  0]
 [ 0 20  0]
 [ 0  0 30]]
Diagonal Values:
 [10 20 30]


### Is In


In [4]:
array = np.random.randint(10, 100, 20)
items = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

available_items = array[np.isin(array, items)]

print("Array:", array)
print("Check Items:", items)
print("Available Items:", available_items)

Array: [78 34 85 33 68 61 26 45 62 76 14 80 94 94 46 87 92 87 39 45]
Check Items: [ 10  20  30  40  50  60  70  80  90 100]
Available Items: [80]


### Unique


In [5]:
array = np.array([2, 4, 1, 5, 6, 7, 2, 1, 3, 8, 3, 6, 2, 4])

print("Array:", array)
print("Array with Unique Elements:", np.unique(array))

Array: [2 4 1 5 6 7 2 1 3 8 3 6 2 4]
Array with Unique Elements: [1 2 3 4 5 6 7 8]


### Clip


In [6]:
array = np.random.randint(1, 100, 10)
clipped_array = np.clip(array, 10, 50)  # <array, min value,max value>

print("Array:", array)
print("Clipped Array:", clipped_array)

Array: [44 28 55 19  2 22 18 38 81 52]
Clipped Array: [44 28 50 19 10 22 18 38 50 50]


### Index of 1D array in n dimensional array


In [7]:
import numpy as np

array = np.random.randint(10, 99, (3, 3, 3))
index = 16
location = tuple(map(int, np.unravel_index(index, array.shape)))

print("Array:\n", array)
print(f"\nLocation of index {index} in shape {array.shape}: {location}")

Array:
 [[[87 43 71]
  [25 10 33]
  [26 83 67]]

 [[50 95 19]
  [71 52 53]
  [98 63 79]]

 [[64 20 94]
  [23 53 62]
  [11 39 64]]]

Location of index 16 in shape (3, 3, 3): (1, 2, 1)


### Expanding Dimensions


In [8]:
c = np.arange(1, 6)
print("Array:", c)
print("Shape:", c.shape)
print("Dimension:", c.ndim)

c_2D = np.expand_dims(c, axis=0)
print("\nExpanded Array (axis = 0):\n", c_2D)
print("Shape:", c_2D.shape)
print("Dimension:", c_2D.ndim)

c_3D = np.expand_dims(c, axis=1)
print("\nExpanded Array (axis = 1):\n", c_3D)
print("Shape:", c_3D.shape)
print("Dimension:", c_3D.ndim)

Array: [1 2 3 4 5]
Shape: (5,)
Dimension: 1

Expanded Array (axis = 0):
 [[1 2 3 4 5]]
Shape: (1, 5)
Dimension: 2

Expanded Array (axis = 1):
 [[1]
 [2]
 [3]
 [4]
 [5]]
Shape: (5, 1)
Dimension: 2


## Argument Functions


### Index of Maximum and Minimum value

- np.argmin()
- np.argmax()


In [9]:
a = np.random.randint(1, 10, 10)

print("Array:", a)
print("Index:", np.arange(a.size))

print("\nMaximum Value:", np.max(a))
print("Position:", np.argmax(a))

print("\nMinimum Value:", np.min(a))
print("Position:", np.argmin(a))

Array: [9 7 2 2 9 1 2 8 1 8]
Index: [0 1 2 3 4 5 6 7 8 9]

Maximum Value: 9
Position: 0

Minimum Value: 1
Position: 5


In [10]:
b = np.random.randint(1, 10, 9).reshape(3, 3)

print("Array:\n", b)
print("Index:\n", np.arange(b.size).reshape(b.shape))

print("\nMaximum Value in Array:", np.max(b))
print("Index:", np.argmax(b))

print("\nMinimum Value in Array:", np.min(b))
print("Index:", np.argmin(b))

print("\nMaximum Value column-wise:", np.max(b, axis=0))
print("Row Index:", np.argmax(b, axis=0))

print("\nMinimum Value row-wise:", np.min(b, axis=1))
print("Column Index:", np.argmin(b, axis=1))

Array:
 [[3 4 3]
 [9 7 8]
 [9 9 7]]
Index:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Maximum Value in Array: 9
Index: 3

Minimum Value in Array: 3
Index: 0

Maximum Value column-wise: [9 9 8]
Row Index: [1 2 1]

Minimum Value row-wise: [3 7 7]
Column Index: [0 1 2]


In [11]:
a = np.random.randint(1, 10, 10)

print("Array:", a)
print("Index:", np.arange(a.size))

print("\nMaximum Value:", np.max(a))
print("Position:", np.argmax(a))

print("\nMinimum Value:", np.min(a))
print("Position:", np.argmin(a))

Array: [6 9 7 3 6 6 1 5 5 9]
Index: [0 1 2 3 4 5 6 7 8 9]

Maximum Value: 9
Position: 1

Minimum Value: 1
Position: 6


In [12]:
b = np.random.randint(1, 10, 9).reshape(3, 3)

print("Array:\n", b)
print("Index:\n", np.arange(b.size).reshape(b.shape))

print("\nMaximum Value in Array:", np.max(b))
print("Index:", np.argmax(b))

print("\nMinimum Value in Array:", np.min(b))
print("Index:", np.argmin(b))

print("\nMaximum Value column-wise:", np.max(b, axis=0))
print("Row Index:", np.argmax(b, axis=0))

print("\nMinimum Value row-wise:", np.min(b, axis=1))
print("Column Index:", np.argmin(b, axis=1))

Array:
 [[7 9 4]
 [6 9 5]
 [5 5 1]]
Index:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Maximum Value in Array: 9
Index: 1

Minimum Value in Array: 1
Index: 8

Maximum Value column-wise: [7 9 5]
Row Index: [0 0 1]

Minimum Value row-wise: [4 5 1]
Column Index: [2 2 2]


### Index of elements Sorted-wise

- np.argsort()


In [13]:
array = np.random.randint(1, 50, 6)
indices = np.argsort(array)
print("Array:", array)
print("Indices of Sorted:", indices)
print("Sorted Array:", array[indices])

Array: [12 31 44 38 32 38]
Indices of Sorted: [0 1 4 3 5 2]
Sorted Array: [12 31 32 38 38 44]


## Trace

- Returns sum of main diagonal


In [14]:
array = array.reshape((2, 3))
trace = np.trace(array)

print("Array:\n", array)
print("Trace:", trace)

Array:
 [[12 31 44]
 [38 32 38]]
Trace: 44


## Repeating


### Repeat

- Returns array with each element repeated `n` times


In [15]:
array = np.arange(3)
repeated = np.repeat(array, 3)

print("Array:", array)
print("Array elements repeated 3 times:", repeated)

Array: [0 1 2]
Array elements repeated 3 times: [0 0 0 1 1 1 2 2 2]


### Tile

- Returns entire array repeated `n` times


In [16]:
array = np.arange(3)
tiled = np.tile(array, 3)

print("Array:", array)
print("Array repeated 3 times:", tiled)

Array: [0 1 2]
Array repeated 3 times: [0 1 2 0 1 2 0 1 2]
