# Numpy Array Operations:


In [71]:
import numpy as np

#### Slicing:


In [72]:
array = np.arange(1, 11)
print("Array:", array)
print("Particular Element:", array[5])
print("Range of Elements:", array[2:9])
print("Range of Elements with step:", array[2:9:2])

Array: [ 1  2  3  4  5  6  7  8  9 10]
Particular Element: 6
Range of Elements: [3 4 5 6 7 8 9]
Range of Elements with step: [3 5 7 9]


In [73]:
# fmt:off
array2D = np.array(
  [
    [1,2,3],
    [4,5,6],
    [7,8,9]
  ]
)
print("Particular Element:",array2D[0,1])
print("Entire Row:",array2D[1])
print("Entire Column:",array2D[:,1])

Particular Element: 2
Entire Row: [4 5 6]
Entire Column: [2 5 8]


##### Sorting:


In [74]:
unsorted = np.array([5, 8, 6, 9, 3, 7, 10, 12, 56, 97, 51])
print("Unsorted Array:", unsorted)
print("Sorted Array:", np.sort(unsorted))

Unsorted Array: [ 5  8  6  9  3  7 10 12 56 97 51]
Sorted Array: [ 3  5  6  7  8  9 10 12 51 56 97]


In [75]:
# fmt:off
unsorted2D = np.array(
  [
    [4,6],
    [7,2],
    [9,5],
  ]
)
print("Unsorted Matrix:\n", unsorted2D)
print("Sort Matrix by Column:\n", np.sort(unsorted2D, axis=0))
print("Sort Matrix by Row:\n", np.sort(unsorted2D, axis=1))

Unsorted Matrix:
 [[4 6]
 [7 2]
 [9 5]]
Sort Matrix by Column:
 [[4 2]
 [7 5]
 [9 6]]
Sort Matrix by Row:
 [[4 6]
 [2 7]
 [5 9]]


### Filter:


In [76]:
numbers = np.arange(1, 11)
even_numbers = numbers[numbers % 2 == 0]
print("Even Numbers:", even_numbers)

Even Numbers: [ 2  4  6  8 10]


#### Mask:


In [77]:
mask = numbers > 5
print("Numbers greater than 5:", numbers[mask])

Numbers greater than 5: [ 6  7  8  9 10]


#### Indexing:


In [78]:
indices = [0, 3, 6, 7]
print(numbers[indices])


[1 4 7 8]


#### Where - returns indices of array which satisfy condition:


In [79]:
where_result = np.where(numbers > 5)  # <condition>
print("Numbers:", numbers)
print("Where result (numbers > 5):", where_result)
print("Greater than 5:", numbers[where_result])

condition_array = np.where(
    numbers > 5, numbers * 10, numbers * 2
)  # <condition, True operation, False operation>

print("Condition Array:", condition_array)

# np.where() is similar to
# for index, value in enumerate(numbers):
#     if value > 5: (condition)
#         numbers[index] = value*10 (True operation)
#     else:
#         numbers[index] = value*2 (False operation)


Numbers: [ 1  2  3  4  5  6  7  8  9 10]
Where result (numbers > 5): (array([5, 6, 7, 8, 9]),)
Greater than 5: [ 6  7  8  9 10]
Condition Array: [  2   4   6   8  10  60  70  80  90 100]


#### Concatenation


In [80]:
array1 = np.arange(0, 6)
array2 = np.arange(6, 11)

combined = np.concatenate((array1, array2))

print("Array 1:", array1)
print("Array 2:", array2)
print("Combined Array:", combined)

Array 1: [0 1 2 3 4 5]
Array 2: [ 6  7  8  9 10]
Combined Array: [ 0  1  2  3  4  5  6  7  8  9 10]


## Adding new Row and Column

$$
\begin{array}{ccc}
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
&
+
&
\begin{bmatrix}
\textcolor{yellow}{5} & \textcolor{yellow}{6}
\end{bmatrix}
\\[1em]
\text{Original} & & \text{New Row}
\end{array}
\quad
\xrightarrow{\text{Vertical Stack}}
\quad
\begin{array}{c}
\begin{bmatrix}
1 & 2 \\
3 & 4 \\
\textcolor{yellow}{5} & \textcolor{yellow}{6}
\end{bmatrix} \\[1.5em]
\text{New Matrix}
\end{array}

\\[3em]

\begin{array}{ccc}
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
&
+
&
\begin{bmatrix}
\textcolor{cyan}{7} \\
\textcolor{cyan}{8}
\end{bmatrix}
\\[1em]
\text{Original} & & \text{New Column}
\end{array}
\quad
\xrightarrow{\text{Horizontal Stack}}
\quad
\begin{array}{c}
\begin{bmatrix}
1 & 2 & \textcolor{cyan}{7} \\
3 & 4 & \textcolor{cyan}{8}
\end{bmatrix} \\[1.5em]
\text{New Matrix}
\end{array}
$$


In [81]:
# fmt:off
original = np.array(
  [
    [1,2],
    [3,4]
  ]
)

new_row = np.array(
  [
    [5,6]
  ]
)

new_column = np.array(
  [
    [7],
    [8]
  ]
)

new_row_matrix = np.vstack((original, new_row))
new_column_matrix = np.hstack((original, new_column))

print("Original:\n", original)

print("\nNew Row:\n", new_row)
print("Matrix with new Row:\n", new_row_matrix)

print("\nNew Column:\n", new_column)
print("\nMatrix with new Column:\n", new_column_matrix)

Original:
 [[1 2]
 [3 4]]

New Row:
 [[5 6]]
Matrix with new Row:
 [[1 2]
 [3 4]
 [5 6]]

New Column:
 [[7]
 [8]]

Matrix with new Column:
 [[1 2 7]
 [3 4 8]]


### Deleting Elements

- Does not delete elements from original array
- Returns new array after deleting elements


In [82]:
array = np.arange(6)
delete_single = np.delete(array, 3)
delete_multiple = np.delete(array, (1, 3, 4))
print("Before Deleting:", array)
print("Deleting single element:", delete_single)
print("Deleting multiple elements:", delete_multiple)
print("After Deleting:", array)

Before Deleting: [0 1 2 3 4 5]
Deleting single element: [0 1 2 4 5]
Deleting multiple elements: [0 2 5]
After Deleting: [0 1 2 3 4 5]
