# Numpy Array Operations:


In [1]:
import numpy as np

#### Slicing:


In [2]:
array = np.arange(1, 11)
print("Array:", array)
print("Particular Element:", array[5])
print("Range of Elements:", array[2:9])
print("Range of Elements with step:", array[2:9:2])

Array: [ 1  2  3  4  5  6  7  8  9 10]
Particular Element: 6
Range of Elements: [3 4 5 6 7 8 9]
Range of Elements with step: [3 5 7 9]


In [3]:
# fmt:off
array2D = np.array(
  [
    [1,2,3],
    [4,5,6],
    [7,8,9]
  ]
)
print("Particular Element:",array2D[0,1])
print("Entire Row:",array2D[1])
print("Entire Column:",array2D[:,1])

Particular Element: 2
Entire Row: [4 5 6]
Entire Column: [2 5 8]


##### Sorting:


In [4]:
unsorted = np.array([5, 8, 6, 9, 3, 7, 10, 12, 56, 97, 51])
print("Unsorted Array:", unsorted)
print("Sorted Array:", np.sort(unsorted))

Unsorted Array: [ 5  8  6  9  3  7 10 12 56 97 51]
Sorted Array: [ 3  5  6  7  8  9 10 12 51 56 97]


In [5]:
# fmt:off
unsorted2D = np.array(
  [
    [4,6],
    [7,2],
    [9,5],
  ]
)
print("Unsorted Matrix:\n", unsorted2D)
print("Sort Matrix by Column:\n", np.sort(unsorted2D, axis=0))
print("Sort Matrix by Row:\n", np.sort(unsorted2D, axis=1))

Unsorted Matrix:
 [[4 6]
 [7 2]
 [9 5]]
Sort Matrix by Column:
 [[4 2]
 [7 5]
 [9 6]]
Sort Matrix by Row:
 [[4 6]
 [2 7]
 [5 9]]


### Filter:


In [6]:
numbers = np.arange(1, 11)
even_numbers = numbers[numbers % 2 == 0]
print("Even Numbers:", even_numbers)

Even Numbers: [ 2  4  6  8 10]


#### Mask:


In [7]:
mask = numbers > 5
print("Numbers greater than 5:", numbers[mask])

Numbers greater than 5: [ 6  7  8  9 10]


#### Indexing:


In [8]:
indices = [0, 3, 6, 7]
print(numbers[indices])


[1 4 7 8]


#### Where - returns indices of array which satisfy condition:


In [9]:
where_result = np.where(numbers > 5)  # <condition>
print("Numbers:", numbers)
print("Where result (numbers > 5):", where_result)
print("Greater than 5:", numbers[where_result])

condition_array = np.where(
    numbers > 5, numbers * 10, numbers * 2
)  # <condition, True operation, False operation>

print("Condition Array:", condition_array)

# np.where() is similar to
# for index, value in enumerate(numbers):
#     if value > 5: (condition)
#         numbers[index] = value*10 (True operation)
#     else:
#         numbers[index] = value*2 (False operation)


Numbers: [ 1  2  3  4  5  6  7  8  9 10]
Where result (numbers > 5): (array([5, 6, 7, 8, 9]),)
Greater than 5: [ 6  7  8  9 10]
Condition Array: [  2   4   6   8  10  60  70  80  90 100]
