# Numpy


In [1]:
import numpy as np

#### Creating Numpy array from list


In [2]:
# 1 dimensional array
array = np.array([1, 2, 3, 4, 5])
print(array)

[1 2 3 4 5]


In [3]:
# 2 dimensional array
array2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array2D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Python list vs Numpy array

- List multiplication will repeat elements
- Numpy array multiplication will perform element-wise multiplication


In [4]:
list = [1, 2, 3]
print("List Multiplication:", list * 2)


List Multiplication: [1, 2, 3, 1, 2, 3]


In [5]:
array = np.array([1, 2, 3])
print("Numpy array Scalar multiplication:", array * 2)
print("Numpy array vector multiplication:", array * [1, 2, 3])

Numpy array Scalar multiplication: [2 4 6]
Numpy array vector multiplication: [1 4 9]


#### Array with range of values


In [6]:
array_range1 = np.arange(10)  # from 0 to 10 (end-1)
array_range2 = np.arange(5, 10)  # from 5 to 9 <start, stop>
array_range3 = np.arange(0, 10, 2)  # from 0 to 9 with step of 2 <start, stop, step>

print("Array from 0 - 9:", array_range1)
print("Array from 5 - 9:", array_range2)
print("Array from 0 - 9 with step of 2:", array_range3)

Array from 0 - 9: [0 1 2 3 4 5 6 7 8 9]
Array from 5 - 9: [5 6 7 8 9]
Array from 0 - 9 with step of 2: [0 2 4 6 8]


#### Ways to Creating Matrix:


##### Zeros Matrix:

$$
\text{zeros} =
\begin{bmatrix}
0 & 0 & 0 \\
0 & 0 & 0 \\
0 & 0 & 0
\end{bmatrix}
$$


In [7]:
zeros = np.zeros((3, 3))
print("Zero Matrix:\n", zeros)

Zero Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


##### Ones Matrix:

$$
\text{ones} =
\begin{bmatrix}
1 & 1 & 1 \\
1 & 1 & 1 \\
1 & 1 & 1
\end{bmatrix}
$$


In [8]:
ones = np.ones((3, 3))
print("Ones Matrix:\n", ones)


Ones Matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


##### Constant Matrix/ Uniform Matrix:

$$
\text{constants} =
\begin{bmatrix}
2 & 2 & 2 \\
2 & 2 & 2 \\
2 & 2 & 2
\end{bmatrix}
$$


In [9]:
constants = np.full((3, 3), 2)
print("Constant Matrix/ Uniform Matrix:\n", constants)

Constant Matrix/ Uniform Matrix:
 [[2 2 2]
 [2 2 2]
 [2 2 2]]


#### Random Matrix:

$$
random =
\begin{bmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33}
\end{bmatrix}
\quad \text{where} \quad a_{ij} \in [0,1)
$$


In [10]:
random = np.random.random((3, 3))
print("Random Matrix:\n", random)

Random Matrix:
 [[0.95062042 0.34736388 0.20072586]
 [0.57620558 0.61628174 0.52648097]
 [0.39124637 0.76352127 0.29630054]]


### Vector, Matrix, and Tensor

$$
\begin{aligned}
\text{Vector:} \quad \mathbf{v} &=
\begin{bmatrix}
x_1 & x_2 & x_3
\end{bmatrix}
\\[2ex]

\text{Matrix:} \quad \mathbf{M} &=
\begin{bmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33}
\end{bmatrix}
\\[5ex]

\text{Tensor:} \quad \mathcal{T} &=
\left[
\begin{array}{ccc}
a_{111} & a_{112} & a_{113} \\
a_{121} & a_{122} & a_{123} \\
a_{131} & a_{132} & a_{133} \\
\end{array}
\right]
\quad
\left[
\begin{array}{ccc}
a_{211} & a_{212} & a_{213} \\
a_{221} & a_{222} & a_{223} \\
a_{231} & a_{232} & a_{233} \\
\end{array}
\right]
\quad
\left[
\begin{array}{ccc}
a_{311} & a_{312} & a_{313} \\
a_{321} & a_{322} & a_{323} \\
a_{331} & a_{332} & a_{333} \\
\end{array}
\right]
\end{aligned}
$$


In [11]:
# fmt: off
vector = np.array([10, 20, 30])
print("Vector:\n", vector)

matrix = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
    ]
)
print("Matrix:\n", matrix)

tensor = np.array(
    [
        [
            [1, 2, 3],
            [4, 5, 6],
            [7, 8, 9],
        ],
        [
            [10, 20, 30],
            [40, 50, 60],
            [70, 80, 90],
        ],
        [
            [100, 200, 300],
            [400, 500, 600],
            [700, 800, 900],
        ],
    ]
)
print("Tensor:\n", tensor)

Vector:
 [10 20 30]
Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Tensor:
 [[[  1   2   3]
  [  4   5   6]
  [  7   8   9]]

 [[ 10  20  30]
  [ 40  50  60]
  [ 70  80  90]]

 [[100 200 300]
  [400 500 600]
  [700 800 900]]]


### Numpy Array properties


In [12]:
array = np.array(
    [  # fmt:skip
        [1, 2, 3],
        [4, 5, 6],
    ]
)
print("Shape:", array.shape)
print("Size:", array.size)
print("Dimension:", array.ndim)
print("Data Type:", array.dtype)

Shape: (2, 3)
Size: 6
Dimension: 2
Data Type: int64


### Array Reshaping:

$$
\begin{array}{c}
\begin{bmatrix}
1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9 & 10 & 11 & 12
\end{bmatrix} \\
(1, 12) \\[1em]
\text{Original}
\end{array}
\quad
\xrightarrow{\text{reshape} \\[1ex]}
\quad
\begin{array}{c}
\begin{bmatrix}
1 & 2 & 3 & 4 \\
5 & 6 & 7 & 8 \\
9 & 10 & 11 & 12
\end{bmatrix} \\
(3, 4) \\[1em]
\text{Reshaped Array}
\end{array}
$$

### Reshaped Matrix Flattening:

$$
\begin{array}{c}
\begin{bmatrix}
1 & 2 & 3 & 4 \\
5 & 6 & 7 & 8 \\
9 & 10 & 11 & 12
\end{bmatrix} \\
(3, 4) \\[1em]
\text{Reshaped Array}
\end{array}
\quad
\xrightarrow{\text{flatten}}
\quad
\begin{array}{c}
\begin{bmatrix}
1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9 & 10 & 11 & 12
\end{bmatrix} \\
(1, 12) \\[1em]
\text{Flattened Array}
\end{array}
$$


In [13]:
array = np.arange(1, 13)
print("Original Array:\n", array)

reshaped = array.reshape((3, 4))
print("\nReshaped Array:\n", reshaped)

flattened = reshaped.flatten()
print("\nFlattened Array:\n", flattened)

Original Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Flattened Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


### Reshaped Array and Ravelled View modifications:

$$
\begin{array}{c}
\begin{bmatrix}
\color{yellow}{100} & 2 & 3 & 4 \\
5 & 6 & 7 & 8 \\
9 & 10 & 11 & 12
\end{bmatrix} \\
(3, 4) \\[1em]
\text{Reshaped Array}
\end{array}
\quad
\xleftrightarrow{\text{reflects}}
\quad
\begin{array}{c}
\begin{bmatrix}
\color{yellow}{100} & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9 & 10 & 11 & 12
\end{bmatrix} \\
(1,12) \\[1em]
\text{Ravelled View}
\end{array}
$$


In [14]:
ravelled = reshaped.ravel()
print("Revelled Array:\n", ravelled)

ravelled[0] = 100
print("\nModified Revelled:\n", ravelled)
print("Updated Reshaped:\n", reshaped)

reshaped[0, 0] = 1000
print("\nModified Reshaped:\n", reshaped)
print("Updated Ravelled:\n", ravelled)


Revelled Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

Modified Revelled:
 [100   2   3   4   5   6   7   8   9  10  11  12]
Updated Reshaped:
 [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]

Modified Reshaped:
 [[1000    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]
Updated Ravelled:
 [1000    2    3    4    5    6    7    8    9   10   11   12]


#### Matrix Transpose


$$
\text{A} =
\begin{array}{c}
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix} \\[1.5em]
\text{Original}
\end{array}
\quad
\text{A}^T =
\begin{array}{c}
\begin{bmatrix}
1 & 4 & 7 \\
2 & 5 & 8 \\
3 & 6 & 9
\end{bmatrix} \\[1.5em]
\text{Transposed}
\end{array}
$$


In [15]:
matrix = np.arange(1, 10).reshape((3, 3))
transposed = matrix.T
print("Original:\n", matrix)
print("Transposed:\n", transposed)

Original:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transposed:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
