# Numpy


In [1]:
import numpy as np

#### Creating Numpy array from list


In [2]:
# 1 dimensional array
array = np.array([1, 2, 3, 4, 5])
print(array)

[1 2 3 4 5]


In [3]:
# 2 dimensional array
# fmt:off
array2D = np.array(
  [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
  ])
print(array2D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Python list vs Numpy array

- List multiplication will repeat elements
- Numpy array multiplication will perform element-wise multiplication


In [4]:
list = [1, 2, 3]
print("List Multiplication:", list * 2)

List Multiplication: [1, 2, 3, 1, 2, 3]


In [5]:
array = np.array([1, 2, 3])
print("Numpy array Scalar multiplication:", array * 2)
print("Numpy array vector multiplication:", array * [1, 2, 3])

Numpy array Scalar multiplication: [2 4 6]
Numpy array vector multiplication: [1 4 9]


#### Array with range of values


In [6]:
array_range1 = np.arange(10)  # from 0 to 10 (end-1)
array_range2 = np.arange(5, 10)  # from 5 to 9 <start, stop>
array_range3 = np.arange(0, 10, 2)  # from 0 to 9 with step of 2 <start, stop, step>

print("Array ranging 0 - 9:", array_range1)
print("Array ranging 5 - 9:", array_range2)
print("Array ranging 0 - 9 with step of 2:", array_range3)

Array ranging 0 - 9: [0 1 2 3 4 5 6 7 8 9]
Array ranging 5 - 9: [5 6 7 8 9]
Array ranging 0 - 9 with step of 2: [0 2 4 6 8]


### Array with equally spaced value for a given range


In [7]:
array_spaced = np.linspace(0, 10, 5)
print("Equally spaced value array ranging 0 - 10:", array_spaced)

Equally spaced value array ranging 0 - 10: [ 0.   2.5  5.   7.5 10. ]


#### Ways to Creating Matrix:


##### Zeros Matrix:

$$
\text{zeros} =
\begin{bmatrix}
0 & 0 & 0 \\
0 & 0 & 0 \\
0 & 0 & 0
\end{bmatrix}
$$


In [8]:
zeros = np.zeros((3, 3))
print("Zero Matrix:\n", zeros)

Zero Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


##### Ones Matrix:

$$
\text{ones} =
\begin{bmatrix}
1 & 1 & 1 \\
1 & 1 & 1 \\
1 & 1 & 1
\end{bmatrix}
$$


In [9]:
ones = np.ones((3, 3))
print("Ones Matrix:\n", ones)

Ones Matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


##### Identity Matrix:

$$
\text{I}_3 =
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}
$$


In [10]:
identity = np.identity(3)
print("Identity Matrix:\n", identity)

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


##### Constant Matrix/ Uniform Matrix:

$$
\text{constants} =
\begin{bmatrix}
2 & 2 & 2 \\
2 & 2 & 2 \\
2 & 2 & 2
\end{bmatrix}
$$


In [11]:
constants = np.full((3, 3), 2)
print("Constant Matrix/ Uniform Matrix:\n", constants)

Constant Matrix/ Uniform Matrix:
 [[2 2 2]
 [2 2 2]
 [2 2 2]]


#### Random Matrix:

$$
random =
\begin{bmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33}
\end{bmatrix}
\quad \text{where} \quad a_{ij} \in [0,1)
$$


In [12]:
random = np.random.random((3, 3))
print("Random Matrix:\n", random)

Random Matrix:
 [[0.75774292 0.04005575 0.72916748]
 [0.31722294 0.85218879 0.11832561]
 [0.27305719 0.7340444  0.87217776]]


### Vector, Matrix, and Tensor

$$
\begin{aligned}
\text{Vector:} \quad \mathbf{V} &=
\begin{bmatrix}
x_1 & x_2 & x_3
\end{bmatrix}
\\[2ex]

\text{Matrix:} \quad \mathbf{M} &=
\begin{bmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33}
\end{bmatrix}
\\[5ex]

\text{Tensor:} \quad \mathcal{T} &=
\left[
\begin{array}{ccc}
a_{111} & a_{112} & a_{113} \\
a_{121} & a_{122} & a_{123} \\
a_{131} & a_{132} & a_{133} \\
\end{array}
\right]
\quad
\left[
\begin{array}{ccc}
a_{211} & a_{212} & a_{213} \\
a_{221} & a_{222} & a_{223} \\
a_{231} & a_{232} & a_{233} \\
\end{array}
\right]
\quad
\left[
\begin{array}{ccc}
a_{311} & a_{312} & a_{313} \\
a_{321} & a_{322} & a_{323} \\
a_{331} & a_{332} & a_{333} \\
\end{array}
\right]
\end{aligned}
$$


In [13]:
# fmt: off
vector = np.array([10, 20, 30])
print("Vector:\n", vector)

matrix = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
    ]
)
print("Matrix:\n", matrix)

tensor = np.array(
    [
        [
            [1, 2, 3],
            [4, 5, 6],
            [7, 8, 9],
        ],
        [
            [10, 20, 30],
            [40, 50, 60],
            [70, 80, 90],
        ],
        [
            [100, 200, 300],
            [400, 500, 600],
            [700, 800, 900],
        ],
    ]
)
print("Tensor:\n", tensor)

Vector:
 [10 20 30]
Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Tensor:
 [[[  1   2   3]
  [  4   5   6]
  [  7   8   9]]

 [[ 10  20  30]
  [ 40  50  60]
  [ 70  80  90]]

 [[100 200 300]
  [400 500 600]
  [700 800 900]]]


### Numpy Array properties:


In [14]:
array = np.array(
    [  # fmt:skip
        [1, 2, 3],
        [4, 5, 6],
    ]
)
print("Shape:", array.shape)
print("Size:", array.size)
print("Dimension:", array.ndim)
print("Data Type:", array.dtype)
print("Item Size:", array.itemsize, "bytes")

Shape: (2, 3)
Size: 6
Dimension: 2
Data Type: int64
Item Size: 8 bytes


##### Changing datatype:

- Returns new array with new Data Type
- Does not affects original array


In [15]:
age = np.array([7, 18, 36, 23, 75, 60, 53, 24, 68, 28, 34, 32])
print("Data Type of Age:", age.dtype)
age_int8 = age.astype(np.uint8)
print("Data Type of Age (int8):", age_int8.dtype)
print("Data Type of Age after Changing:", age.dtype)

Data Type of Age: int64
Data Type of Age (int8): uint8
Data Type of Age after Changing: int64


## Array Operations:


### Array Reshaping:

$$
\begin{array}{c}
\begin{bmatrix}
1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9 & 10 & 11 & 12
\end{bmatrix} \\
(1, 12) \\[1em]
\text{Original}
\end{array}
\quad
\xrightarrow{\text{reshape} \\[1ex]}
\quad
\begin{array}{c}
\begin{bmatrix}
1 & 2 & 3 & 4 \\
5 & 6 & 7 & 8 \\
9 & 10 & 11 & 12
\end{bmatrix} \\
(3, 4) \\[1em]
\text{Reshaped Array}
\end{array}
$$

### Reshaped Matrix Flattening:

$$
\begin{array}{c}
\begin{bmatrix}
1 & 2 & 3 & 4 \\
5 & 6 & 7 & 8 \\
9 & 10 & 11 & 12
\end{bmatrix} \\
(3, 4) \\[1em]
\text{Reshaped Array}
\end{array}
\quad
\xrightarrow{\text{flatten}}
\quad
\begin{array}{c}
\begin{bmatrix}
1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9 & 10 & 11 & 12
\end{bmatrix} \\
(1, 12) \\[1em]
\text{Flattened Array}
\end{array}
$$


In [16]:
array = np.arange(1, 13)
print("Original Array:\n", array)

reshaped = array.reshape((3, 4))
print("\nReshaped Array:\n", reshaped)

flattened = reshaped.flatten()
print("\nFlattened Array:\n", flattened)

Original Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Flattened Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


### Reshaped Array and Ravelled View modifications:

$$
\begin{array}{c}
\begin{bmatrix}
\color{yellow}{100} & 2 & 3 & 4 \\
5 & 6 & 7 & 8 \\
9 & 10 & 11 & 12
\end{bmatrix} \\
(3, 4) \\[1em]
\text{Reshaped Array}
\end{array}
\quad
\xleftrightarrow{\text{reflects}}
\quad
\begin{array}{c}
\begin{bmatrix}
\color{yellow}{100} & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9 & 10 & 11 & 12
\end{bmatrix} \\
(1,12) \\[1em]
\text{Ravelled View}
\end{array}
$$


In [17]:
ravelled = reshaped.ravel()
print("Revelled View:\n", ravelled)

ravelled[0] = 100
print("\nModified Revelled:\n", ravelled)
print("Updated Reshaped:\n", reshaped)

reshaped[0, 0] = 1000
print("\nModified Reshaped:\n", reshaped)
print("Updated Ravelled:\n", ravelled)

Revelled View:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

Modified Revelled:
 [100   2   3   4   5   6   7   8   9  10  11  12]
Updated Reshaped:
 [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]

Modified Reshaped:
 [[1000    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]
Updated Ravelled:
 [1000    2    3    4    5    6    7    8    9   10   11   12]


### Matrix Transpose

$$
\text{A} =
\begin{array}{c}
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix} \\[1.5em]
\text{Original}
\end{array}
\quad
\text{A}^T =
\begin{array}{c}
\begin{bmatrix}
1 & 4 & 7 \\
2 & 5 & 8 \\
3 & 6 & 9
\end{bmatrix} \\[1.5em]
\text{Transposed}
\end{array}
$$


In [18]:
matrix = np.arange(1, 10).reshape((3, 3))
transposed = matrix.T  # Alternative: np.transpose(array)
print("Original:\n", matrix)
print("Transposed:\n", transposed)

Original:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transposed:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


#### Arithmetic Operations:


In [19]:
array = np.arange(1, 10).reshape((3, 3))

## Performs operation for every elements of array
print("Array:\n", array * 2)
print("Array * 2:\n", array * 2)

Array:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Array * 2:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [20]:
array1 = np.arange(1, 10).reshape((3, 3))
array2 = np.arange(10, 19).reshape((3, 3))

print("Array 1:\n", array1)
print("Array 2:\n", array2)

## Element-wise addition
print("\nArray 1 + Array 2:\n", array1 + array2)

Array 1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array 2:
 [[10 11 12]
 [13 14 15]
 [16 17 18]]

Array 1 + Array 2:
 [[11 13 15]
 [17 19 21]
 [23 25 27]]


#### Relational Operation:


In [21]:
print("Array > 5:\n", array > 5)

Array > 5:
 [[False False False]
 [False False  True]
 [ True  True  True]]


### Array Funtions:


In [22]:
array = np.random.random((2, 3)) * 100
print("Array:\n", array)

round_array = np.round(array)
round_array = round_array.astype(np.int8)
print("\nRounded Array:\n", round_array)

ceil_array = np.ceil(array)
ceil_array = ceil_array.astype(np.int8)
print("\nCeil Array:\n", ceil_array)

floor_array = np.floor(array)
floor_array = floor_array.astype(np.int8)
print("\nFloor Array:\n", floor_array)

Array:
 [[65.13407045 59.82009712 41.82739999]
 [35.75898594 94.93093349 22.20625934]]

Rounded Array:
 [[65 60 42]
 [36 95 22]]

Ceil Array:
 [[66 60 42]
 [36 95 23]]

Floor Array:
 [[65 59 41]
 [35 94 22]]


In [23]:
min_value = np.min(array)
max_value = np.max(array)
sum_value = np.sum(array)
sum_value_column = np.sum(array, axis=0)
sum_value_row = np.sum(array, axis=1)
prod_value = np.prod(array)

print("Minimum:", min_value)
print("Maximum:", max_value)
print("Sum:", sum_value)
print("Sum along Column:", sum_value_column)
print("Sum along Row:", sum_value_row)
print("Product:", prod_value)

Minimum: 22.206259335889346
Maximum: 94.93093348883329
Sum: 319.67774632911363
Sum along Column: [100.89305639 154.75103061  64.03365933]
Sum along Row: [166.78156756 152.89617877]
Product: 12285265774.465837


In [24]:
average_value = np.mean(array)
median_value = np.median(array)
standard_deviation_value = np.std(array)
variance_value = np.var(array)

print("Average:", average_value)
print("Median:", median_value)
print("Standard Deviation:", standard_deviation_value)
print("Variance:", variance_value)

Average: 53.2796243881856
Median: 50.82374855606814
Standard Deviation: 23.529476037160293
Variance: 553.6362425833005


In [25]:
array = np.random.random((1, 3))
sin_array = np.sin(array)
cos_array = np.cosh(array)
arctan_array = np.arctan(array)
degree_array = np.degrees(array)  ## Alternative: np.rad2deg
radian_array = np.radians(array)  # Alternative: np.deg2rad

print("Sin:", sin_array)
print("Hyperbolic Cos:", cos_array)
print("Tan Inverse:", arctan_array)
print("Degree:", degree_array)
print("Radian:", radian_array)

Sin: [[0.44517385 0.67877687 0.36595407]]
Hyperbolic Cos: [[1.10833175 1.29148261 1.07100905]]
Tan Inverse: [[0.43226757 0.6409977  0.35847061]]
Degree: [[26.43446221 42.74813717 21.46630965]]
Radian: [[0.0080524  0.01302183 0.00653901]]


#### Dot Product:

$$

A = \begin{bmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23}
\end{bmatrix}

\\[2ex]

B = \begin{bmatrix}
b_{11} & b_{12} \\
b_{21} & b_{22} \\
b_{31} & b_{32}
\end{bmatrix}

\\[2ex]

A \cdot B
= \begin{bmatrix}
a_{11}b_{11} + a_{12}b_{21} + a_{13}b_{31} &
a_{11}b_{12} + a_{12}b_{22} + a_{13}b_{32} \\
a_{21}b_{11} + a_{22}b_{21} + a_{23}b_{31} &
a_{21}b_{12} + a_{22}b_{22} + a_{23}b_{32}
\end{bmatrix}


$$


In [26]:
matrix1 = np.arange(1, 7).reshape((2, 3))
matrix2 = np.arange(7, 13).reshape((3, 2))
dot_product = np.dot(matrix1, matrix2)  # Alternative: matrix1 @ matrix2

print(f"Dot Product: \nA = \n{matrix1}\nB = \n{matrix2}\n\nA · B = \n{dot_product}")

Dot Product: 
A = 
[[1 2 3]
 [4 5 6]]
B = 
[[ 7  8]
 [ 9 10]
 [11 12]]

A · B = 
[[ 58  64]
 [139 154]]
